name: Preview NuGet package

on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+-rc.[0-9]+"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set VERSION variable from tag
        run: echo "VERSION=${GITHUB_REF/refs\/tags\/v/}" >> $GITHUB_ENV

      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build -c Release /p:Version=${VERSION}

      - name: Test
        run: dotnet test -c Release /p:Version=${VERSION} --no-restore --verbosity normal

      - name: Pack
        run: dotnet pack ./src/Z80Cpu/Z80Cpu.csproj -c Release /p:Version=${VERSION} -p:PackageID=${{ vars.PACKAGE_NAME }} --no-restore --output .

      - name: Push
        run: dotnet nuget push ${{ vars.PACKAGE_NAME }}.${VERSION}.nupkg --source https://api.nuget.org/v3/index.json --api-key ${{ secrets.NUGET_KEY }}