name: Publish NuGet package

on:
  workflow_dispatch:
    inputs:
      publishPreRelease:
        description: 'Publish pre-release'
        type: boolean

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install GitVersion
        uses: gittools/actions/gitversion/setup@v3.1.11
        with:
          versionSpec: '6.0.x'

      - name: Determine version
        id: version_step
        uses: gittools/actions/gitversion/execute@v3.1.11

      - name: Set package name
        run: |
          branch=${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}
          if [ "$branch" == "spectron" ]; then
            echo "PACKAGE_NAME=OldBit.Z80Cpu.Spectron" >> $GITHUB_ENV
          else
             echo "PACKAGE_NAME=OldBit.Z80Cpu" >> $GITHUB_ENV
          fi

      - name: Set version
        run: |
          version=${{ steps.version_step.outputs.majorMinorPatch }}
          echo "VERSION=$version" >> $GITHUB_ENV

      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build -c Release /p:Version=${VERSION}

#      - name: Test
#        run: dotnet test -c Release /p:Version=${VERSION} --no-restore --verbosity normal

#      - name: Pack
#        run: dotnet pack ./src/Z80Cpu/Z80Cpu.csproj -c Release /p:Version=${VERSION} -p:PackageID=${{ vars.PACKAGE_NAME }} --no-restore --output .

#      - name: Push
#        run: dotnet nuget push ${{ vars.PACKAGE_NAME }}.${VERSION}.nupkg --source https://api.nuget.org/v3/index.json --api-key ${{ secrets.NUGET_KEY }}